# For full config options, check the docs:
#    docs.serverless.com
service: product-service

plugins:
  - serverless-plugin-typescript

configValidationMode: warn

provider:
  name: aws
  runtime: nodejs16.x
  stage: "dev"
  region: eu-west-1
  profile: aws
  environment:
    PG_HOST: awsdb.c2cf02vn1xvw.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DB_NAME: awsdb
    PG_USERNAME: postgres
    PG_PASSWORD: 0dwrJFVYpcjXCKBMpccN


functions:
  getProductList:
    handler: src/handlers/getProductList.handler
    description: getProductList to get products
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: src/handlers/getProductsById.handler
    description: get product by id from available list
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  pgLambdaInit:
    handler: src/handlers/pgLambdaInit.handler
    description: create tables of data
  createProduct:
    handler: src/handlers/createProduct.handler
    description: create product
    events:
      - http:
          path: products
          method: post
          cors: true
              
            